from utils.llm_client import UnifiedLLMClient
from utils.judge_prompts import preference_signal_prompt, reasoning_depth_prompt, strategic_responding_prompt, coherehnce_prompt, format_compliance_prompt, combined_judge_prompt

class JudgeClient:
    """
    LLm-as-a-judge client to evaluate the quality of generated responses
    The client evaluates the generated response based on a set of criteria, such as preference signal strength, reasoning depth, strategic response, coherence and format compliance
    Judge format can be "combined" or "individual". Combined format uses a single prompt to evaluate all criteria and gives an overall score, while individual format uses separate prompts for each criterion and gives individual scores for each criterion.
    """

    def __init__(self, model: str = "gpt-4o", temperature: float = 0.0, judge_format: str = "combined"):
        """
        Args:
            model: The LLM model to use for evaluation. 
            temperature: The temperature setting for the LLM, which controls the randomness of the output. 
            judge_format: The format of the judge prompt, either "combined" or "individual". 
        """
        name = model.lower()
        if "gpt" in name:
            self.provider = "openai"
        elif "claude" in name:
            self.provider = "anthropic"
        elif "gemini" in name:
            self.provider = "google"
        else:
            raise ValueError(f"Unsupported model: {model}")

        self.client = UnifiedLLMClient(provider=self.provider, model=model)
        self.temperature = temperature

    def evaluate_response(self, scenario_context, action_a, action_b, model_response, metadata=None):
        """
        Evaluate the model response based on the given scenario context and actions.
        Args:
            scenario_context: The context of the scenario being evaluated.
            action_a: The first action option in the scenario.
            action_b: The second action option in the scenario.
            model_response: The response generated by the model for the given scenario and actions.
        Returns:
            A dictionary containing the evaluation scores for each criterion, as well as an overall score if using the combined judge format.
        """

        prompt_id = metadata["prompt_id"]
        parts = prompt_id.split("-")

        response_format = parts[2]   
        action_order = parts[5]

        if action_order == "regular":
            opt1 = action_a
            opt2 = action_b
        else:  # inverted
            opt1 = action_b
            opt2 = action_a

        options_block = ""
        if response_format == "2o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n"
        elif response_format == "3o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n Option C:No strong preference / Both equally acceptable\n"
        elif response_format == "4o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n Option C: Both equally acceptable\n Option D: Neither acceptable\n"
        else:
            raise ValueError(f"Unsupported response format: {response_format}")
        
        if self.judge_format == "combined":
            prompt = combined_judge_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )
            evaluation = self.client.generate(prompt)
            return {"overall_score": evaluation.strip()}
        else:
            preference_signal_score = self.client.generate(preference_signal_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            reasoning_depth_score = self.client.generate(reasoning_depth_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            strategic_responding_score = self.client.generate(strategic_responding_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            coherence_score = self.client.generate(coherehnce_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            format_compliance_score = self.client.generate(format_compliance_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            return {
                "preference_signal_score": preference_signal_score,
                "reasoning_depth_score": reasoning_depth_score,
                "strategic_responding_score": strategic_responding_score,
                "coherence_score": coherence_score,
                "format_compliance_score": format_compliance_score
            }

        