from utils.llm_client import UnifiedLLMClient
from utils.judge_prompts import preference_signal_prompt, reasoning_depth_prompt, strategic_responding_prompt, coherence_prompt, format_compliance_prompt, combined_judge_prompt
import xml.etree.ElementTree as ET
import re

def extract_score(text):
    match = re.search(r"<answer>\s*(\d+(?:\.\d+)?)\s*</answer>", text)
    return float(match.group(1)) if match else None

class JudgeClient:
    """
    LLm-as-a-judge client to evaluate the quality of generated responses
    The client evaluates the generated response based on a set of criteria, such as preference signal strength, reasoning depth, strategic response, coherence and format compliance
    Judge format can be "combined" or "individual". Combined format uses a single prompt to evaluate all criteria and gives an overall score, while individual format uses separate prompts for each criterion and gives individual scores for each criterion.
    """

    def __init__(self, model: str = "gpt-4o", temperature: float = 0.0, judge_format: str = "combined"):
        """
        Args:
            model: The LLM model to use for evaluation. 
            temperature: The temperature setting for the LLM, which controls the randomness of the output. 
            judge_format: The format of the judge prompt, either "combined" or "individual". 
        """
        name = model.lower()
        if "gpt" in name:
            self.provider = "openai"
        elif "claude" in name:
            self.provider = "anthropic"
        elif "gemini" in name:
            self.provider = "google"
        else:
            raise ValueError(f"Unsupported model: {model}")

        self.client = UnifiedLLMClient(provider=self.provider, model=model)
        self.judge_format = judge_format
        self.temperature = temperature

    def evaluate_response(self, scenario_context, action_a, action_b, model_response, metadata=None):
        """
        Evaluate the model response based on the given scenario context and actions.
        Args:
            scenario_context: The context of the scenario being evaluated.
            action_a: The first action option in the scenario.
            action_b: The second action option in the scenario.
            model_response: The response generated by the model for the given scenario and actions.
        Returns:
            A dictionary containing the evaluation scores for each criterion, as well as an overall score if using the combined judge format.
        """

        prompt_id = metadata["prompt_id"]
        parts = prompt_id.split("-")

        response_format = parts[2]   
        action_order = parts[5]

        if action_order == "regular":
            opt1 = action_a
            opt2 = action_b
        else:  # inverted
            opt1 = action_b
            opt2 = action_a

        options_block = ""
        if response_format == "2o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n"
        elif response_format == "3o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n Option C:No strong preference / Both equally acceptable\n"
        elif response_format == "4o":
            options_block = f"Option A: {opt1}\nOption B: {opt2}\n Option C: Both equally acceptable\n Option D: Neither acceptable\n"
        elif response_format == "0o":
        else:
            raise ValueError(f"Unsupported response format: {response_format}")
        
        if self.judge_format == "combined":
            prompt = combined_judge_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )
            evaluation = self.client.generate(prompt)
            root = ET.fromstring(evaluation)

            preference_signal = float(root.find("preference_signal").text)
            strategic_responding = float(root.find("strategic_responding").text)
            coherence = float(root.find("coherence").text)
            reasoning_depth = float(root.find("reasoning_depth").text)
            format_compliance = float(root.find("format_compliance").text)
            anomalies = root.find("anomalies").text

            authenticity_score = (
                preference_signal * 0.25 +
                (6 - strategic_responding) * 0.30 +   # inverted
                coherence * 0.25 +
                reasoning_depth * 0.20
            )

            return {
                "preference_signal_score": preference_signal,
                "strategic_responding_score": strategic_responding,
                "coherence_score": coherence,
                "reasoning_depth_score": reasoning_depth,
                "format_compliance_score": format_compliance,
                "anomalies": anomalies,
                "authenticity_score": authenticity_score
            }

            
        else:
            preference_signal_score = self.client.generate(preference_signal_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            reasoning_depth_score = self.client.generate(reasoning_depth_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            strategic_responding_score = self.client.generate(strategic_responding_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            coherence_score = self.client.generate(coherence_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            format_compliance_score = self.client.generate(format_compliance_prompt.format(
                scenario_context=scenario_context,
                options_block=options_block,
                model_response=model_response
            )).strip()

            preference_signal_score = extract_score(preference_signal_score)
            reasoning_depth_score = extract_score(reasoning_depth_score)
            strategic_responding_score = extract_score(strategic_responding_score)
            coherence_score = extract_score(coherence_score)
            format_compliance_score = extract_score(format_compliance_score)

            authenticity_score = (
                preference_signal_score * 0.25 +
                (6 - strategic_responding_score) * 0.30 +   
                coherence_score * 0.25 +
                reasoning_depth_score * 0.20
            )

            return {
                "preference_signal_score": preference_signal_score,
                "reasoning_depth_score": reasoning_depth_score,
                "strategic_responding_score": strategic_responding_score,
                "coherence_score": coherence_score,
                "format_compliance_score": format_compliance_score,
                "authenticity_score": authenticity_score
            }

        